# Generated by Django 2.1 on 2021-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201231_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='max_consecutive',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
