# Generated by Django 2.1 on 2020-11-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='joinexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='joinexercise', to='exercise.Exercise'),
        ),
        migrations.AlterField(
            model_name='joinexercise',
            name='last_join',
            field=models.DateField(auto_now=True),
        ),
    ]
