# Generated by Django 2.1 on 2020-12-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20201130_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinexercise',
            old_name='last_join',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='joinexercise',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='joinexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='joinexercise',
            name='percentage',
        ),
    ]
